# Generated by Django 5.2.11 on 2026-02-08 07:49

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Klinik Adı')),
                ('address', models.TextField(verbose_name='Adres')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Klinik',
                'verbose_name_plural': 'Klinikler',
            },
        ),
        migrations.CreateModel(
            name='ClinicUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'Klinik Yöneticisi'), ('assistant', 'Asistan'), ('doctor', 'Doktor')], default='assistant', max_length=20, verbose_name='Rol')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='clinic.clinic', verbose_name='Klinik')),
            ],
            options={
                'verbose_name': 'Kullanıcı',
                'verbose_name_plural': 'Kullanıcılar',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ClinicSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('trial', 'Deneme'), ('basic', 'Temel'), ('professional', 'Profesyonel'), ('enterprise', 'Kurumsal')], default='trial', max_length=20, verbose_name='Plan')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('max_dentists', models.IntegerField(default=3, verbose_name='Maks. Hekim Sayısı')),
                ('max_appointments_per_month', models.IntegerField(default=100, verbose_name='Aylık Maks. Randevu')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('clinic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='clinic.clinic', verbose_name='Klinik')),
            ],
            options={
                'verbose_name': 'Abonelik',
                'verbose_name_plural': 'Abonelikler',
            },
        ),
        migrations.CreateModel(
            name='Dentist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Ad Soyad')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('specialty', models.CharField(max_length=100, verbose_name='Uzmanlık Alanı')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-posta')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dentists', to='clinic.clinic', verbose_name='Klinik')),
            ],
            options={
                'verbose_name': 'Diş Hekimi',
                'verbose_name_plural': 'Diş Hekimleri',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Ad Soyad')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-posta')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Doğum Tarihi')),
                ('blood_type', models.CharField(choices=[('A+', 'A Rh+'), ('A-', 'A Rh-'), ('B+', 'B Rh+'), ('B-', 'B Rh-'), ('AB+', 'AB Rh+'), ('AB-', 'AB Rh-'), ('0+', '0 Rh+'), ('0-', '0 Rh-'), ('unknown', 'Bilinmiyor')], default='unknown', max_length=10, verbose_name='Kan Grubu')),
                ('allergies', models.TextField(blank=True, help_text='Bilinen alerjiler (ilaç, lateks vb.)', verbose_name='Alerjiler')),
                ('chronic_diseases', models.TextField(blank=True, help_text='Diyabet, hipertansiyon, kalp hastalığı vb.', verbose_name='Kronik Hastalıklar')),
                ('current_medications', models.TextField(blank=True, help_text='Düzenli kullanılan ilaçlar', verbose_name='Kullanılan İlaçlar')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=200, verbose_name='Acil Durum Kişisi')),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Acil Durum Telefonu')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('sms_consent', models.BooleanField(default=True, verbose_name='SMS İzni')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='clinic.clinic', verbose_name='Klinik')),
            ],
            options={
                'verbose_name': 'Hasta',
                'verbose_name_plural': 'Hastalar',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Başlangıç Saati')),
                ('end_time', models.DateTimeField(verbose_name='Bitiş Saati')),
                ('status', models.CharField(choices=[('scheduled', 'Planlandı'), ('confirmed', 'Onaylandı'), ('completed', 'Tamamlandı'), ('cancelled', 'İptal Edildi'), ('no_show', 'Gelmedi')], default='scheduled', max_length=20, verbose_name='Durum')),
                ('treatment_type', models.CharField(blank=True, max_length=100, verbose_name='Tedavi Türü')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dentist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='clinic.dentist', verbose_name='Diş Hekimi')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='clinic.patient', verbose_name='Hasta')),
            ],
            options={
                'verbose_name': 'Randevu',
                'verbose_name_plural': 'Randevular',
                'ordering': ['start_time'],
            },
        ),
    ]
